# Generated by Django 5.2.7 on 2025-11-19 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Course subject code (e.g., BSCS125781)', max_length=50)),
                ('subject_name', models.CharField(blank=True, help_text='Name/title of the course', max_length=255)),
                ('start_time', models.CharField(help_text='Class start time (e.g., 07:00AM)', max_length=20)),
                ('end_time', models.CharField(help_text='Class end time (e.g., 09:00AM)', max_length=20)),
                ('day', models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('TF', 'Tuesday-Friday'), ('MW', 'Monday-Wednesday'), ('MWF', 'Monday-Wednesday-Friday'), ('MTH', 'Monday-Thursday'), ('TTH', 'Tuesday-Thursday')], help_text='Day(s) of the week the class meets', max_length=10)),
                ('location', models.CharField(blank=True, help_text='Classroom/location (e.g., LR7, LAB2)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this course schedule', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['day', 'start_time'],
                'indexes': [models.Index(fields=['user', 'subject_code'], name='api_course_user_id_da18eb_idx'), models.Index(fields=['user', 'day'], name='api_course_user_id_39815d_idx')],
            },
        ),
    ]
