# Generated by Django 5.2.7 on 2025-12-02 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='User-defined name for this schedule', max_length=255)),
                ('upload_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], help_text='Type of schedule: student or faculty', max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active schedule for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='The schedule this course belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.schedule'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'upload_type'], name='api_schedul_user_id_59df66_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'is_active'], name='api_schedul_user_id_8434ee_idx'),
        ),
    ]
