# Generated by Django 5.2.7 on 2025-12-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_schedule_course_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timetable_image',
            field=models.ImageField(blank=True, help_text='Auto-generated timetable image for this schedule', null=True, upload_to='timetables/'),
        ),
    ]
