# Generated by Django 5.2.7 on 2026-01-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token for this device', max_length=100, null=True),
        ),
    ]
