# Generated by Django 5.2.7 on 2026-01-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_expo_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='upload_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('merged', 'Merged')], help_text='Type of schedule: student or faculty', max_length=10),
        ),
    ]
