# Generated by Django 5.2.7 on 2026-01-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_schedule_upload_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty')], help_text='Original source schedule type (for merged schedules)', max_length=10, null=True),
        ),
    ]
