# Generated by Django 5.2.7 on 2026-02-05 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('parent', 'Parent')], default='student', help_text='Type of user account: student, faculty, or parent', max_length=10),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='10-character alphanumeric invite code', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code is still valid')),
                ('used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the code was used', null=True)),
                ('student', models.ForeignKey(help_text='The student who generated this code', on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, help_text='The parent who used this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Code',
                'verbose_name_plural': 'Invite Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', help_text='Status of the parent-child link', max_length=10)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(help_text='The student (child) user', on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
                ('parent', models.OneToOneField(help_text='The parent user', on_delete=django.db.models.deletion.CASCADE, related_name='child_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent-Child Link',
                'verbose_name_plural': 'Parent-Child Links',
            },
        ),
    ]
