# Generated by Django 5.2.7 on 2026-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_parental_view_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['code'], name='api_invitec_code_1ced28_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['student', 'is_active', 'used'], name='api_invitec_student_e2eab5_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildlink',
            index=models.Index(fields=['parent', 'status'], name='api_parentc_parent__587078_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildlink',
            index=models.Index(fields=['child', 'status'], name='api_parentc_child_i_b56e39_idx'),
        ),
    ]
