# Generated by Django 5.2.7 on 2026-02-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_parental_view_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('reset_token', models.UUIDField(blank=True, help_text='UUID token issued after code verification, used to set new password', null=True, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this code/token has been fully used to reset the password')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the 6-digit code has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this code expires (10 minutes after creation)')),
            ],
            options={
                'verbose_name': 'Password Reset Code',
                'verbose_name_plural': 'Password Reset Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='parentchildlink',
            name='parent',
            field=models.ForeignKey(help_text='The parent user', on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='parentchildlink',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('parent', 'child'), name='unique_active_parent_child_link'),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(help_text='The user requesting a password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'code'], name='api_passwor_user_id_d63dea_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['reset_token'], name='api_passwor_reset_t_38d073_idx'),
        ),
    ]
