# Generated by Django 5.2.7 on 2026-02-15 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_passwordresetcode_alter_parentchildlink_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Subject code this task is for', max_length=50)),
                ('text', models.CharField(help_text='Task description/content', max_length=500)),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional due date for the task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='The faculty who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Task',
                'verbose_name_plural': 'Faculty Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the student has completed this task')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the student completed this task', null=True)),
                ('student', models.ForeignKey(help_text='The student who completed/has this task', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_task_completions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='The faculty task', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.facultytask')),
            ],
            options={
                'verbose_name': 'Faculty Task Completion',
                'verbose_name_plural': 'Faculty Task Completions',
            },
        ),
        migrations.CreateModel(
            name='ClassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Subject code this class code is for', max_length=50)),
                ('code', models.CharField(help_text='8-character alphanumeric class code', max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code is still valid for enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(help_text='The faculty who generated this code', on_delete=django.db.models.deletion.CASCADE, related_name='class_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Code',
                'verbose_name_plural': 'Class Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='api_classco_code_b5fe7c_idx'), models.Index(fields=['faculty', 'subject_code', 'is_active'], name='api_classco_faculty_3eef52_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Subject code for this enrollment', max_length=50)),
                ('enrollment_type', models.CharField(choices=[('auto', 'Auto-matched'), ('code', 'Via class code')], default='code', help_text='How the student was enrolled', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', help_text='Status of the enrollment', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(help_text='The faculty member teaching the class', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student enrolled in the class', on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['faculty', 'subject_code', 'status'], name='api_classen_faculty_edf8fa_idx'), models.Index(fields=['student', 'subject_code', 'status'], name='api_classen_student_e6facf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'faculty', 'subject_code'), name='unique_active_enrollment')],
            },
        ),
        migrations.AddIndex(
            model_name='facultytask',
            index=models.Index(fields=['faculty', 'subject_code'], name='api_faculty_faculty_33d434_idx'),
        ),
        migrations.AddIndex(
            model_name='facultytaskcompletion',
            index=models.Index(fields=['task', 'is_completed'], name='api_faculty_task_id_3cc89d_idx'),
        ),
        migrations.AddIndex(
            model_name='facultytaskcompletion',
            index=models.Index(fields=['student', 'is_completed'], name='api_faculty_student_27d404_idx'),
        ),
        migrations.AddConstraint(
            model_name='facultytaskcompletion',
            constraint=models.UniqueConstraint(fields=('task', 'student'), name='unique_task_completion'),
        ),
    ]
