# Generated by Django 5.2.7 on 2026-02-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_facultytask_facultytaskcompletion_classcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytask',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file attachment (PDF, image, Word, PowerPoint)', null=True, upload_to='faculty_files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='facultytask',
            name='file_name',
            field=models.CharField(blank=True, default='', help_text='Original filename of the uploaded file', max_length=255),
        ),
    ]
