# Generated by Django 5.2.7 on 2026-02-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_facultytask_file_facultytask_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultytask',
            name='file',
            field=models.FileField(blank=True, help_text='(Legacy) Single file attachment — use FacultyTaskFile for new uploads', null=True, upload_to='faculty_files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='facultytask',
            name='file_name',
            field=models.CharField(blank=True, default='', help_text='(Legacy) Original filename of the uploaded file', max_length=255),
        ),
        migrations.CreateModel(
            name='FacultyTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded file', upload_to='faculty_files/%Y/%m/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='The task this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.facultytask')),
            ],
            options={
                'verbose_name': 'Faculty Task File',
                'verbose_name_plural': 'Faculty Task Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
