# Generated by Django 5.2.7 on 2026-02-26 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_faculty_task_file_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('class_reminder', 'Class Reminder'), ('faculty_task', 'Faculty Task'), ('general', 'General')], default='general', help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification body text')),
                ('data', models.JSONField(blank=True, help_text='Extra data payload (e.g. subject_code, task_id)', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='api_notific_user_id_16328d_idx'), models.Index(fields=['user', 'notification_type'], name='api_notific_user_id_5b04a6_idx'), models.Index(fields=['user', '-created_at'], name='api_notific_user_id_48bbdc_idx')],
            },
        ),
    ]
