# Generated by Django 5.2.7 on 2026-02-28 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Subject code for this remark', max_length=50)),
                ('text', models.TextField(help_text='The remark / comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='The faculty who wrote this remark', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_remarks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student this remark is about', on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Remark',
                'verbose_name_plural': 'Faculty Remarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['faculty', 'subject_code'], name='api_faculty_faculty_7099fb_idx'), models.Index(fields=['student', 'subject_code'], name='api_faculty_student_1326b0_idx'), models.Index(fields=['student', '-created_at'], name='api_faculty_student_d24234_idx')],
            },
        ),
    ]
