# Generated by Django 5.2.7 on 2026-03-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_faculty_remark_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='school_year',
            field=models.CharField(blank=True, default='', help_text="School year (e.g., '2025-2026')", max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(blank=True, default='', help_text="Semester (e.g., '1ST', '2ND', 'SUMMER')", max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('class_reminder', 'Class Reminder'), ('faculty_task', 'Faculty Task'), ('faculty_remark', 'Faculty Remark'), ('general', 'General')], default='general', help_text='Type of notification', max_length=20),
        ),
    ]
