# Generated by Django 5.2.7 on 2026-03-05 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_schedule_semester_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_session_id', models.CharField(help_text='Stripe Checkout Session ID', max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID (set after payment completes)', max_length=255, null=True)),
                ('amount', models.IntegerField(help_text='Amount in centavos (e.g. 8900 = ₱89.00)')),
                ('currency', models.CharField(default='php', help_text='Payment currency', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=10)),
                ('child_slot_number', models.IntegerField(help_text='Which child slot this payment unlocks (2 = second child, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the payment was completed', null=True)),
                ('parent', models.ForeignKey(help_text='The parent who made this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', 'status'], name='api_payment_parent__20c77f_idx'), models.Index(fields=['stripe_checkout_session_id'], name='api_payment_stripe__c956c4_idx')],
            },
        ),
    ]
