# Generated by Django 5.2.7 on 2026-03-08 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_deactivated', 'User Deactivated'), ('user_reactivated', 'User Reactivated'), ('holiday_created', 'Holiday Created'), ('holiday_updated', 'Holiday Updated'), ('holiday_deleted', 'Holiday Deleted'), ('admin_login', 'Admin Login')], help_text='The type of action performed', max_length=30)),
                ('target_type', models.CharField(blank=True, default='', help_text="The model type affected (e.g. 'User', 'Holiday')", max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the affected object', null=True)),
                ('detail', models.TextField(blank=True, default='', help_text='Human-readable description of what changed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin at time of action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='The admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='api_adminau_admin_i_367c1d_idx'), models.Index(fields=['action'], name='api_adminau_action_9ce243_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/title of the holiday', max_length=200)),
                ('date', models.DateField(help_text='Date of the holiday (for recurring: only month+day matter)')),
                ('holiday_type', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring')], default='one_time', help_text='Whether this holiday repeats annually', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='api_holiday_date_1a4423_idx'), models.Index(fields=['holiday_type'], name='api_holiday_holiday_8cd371_idx')],
            },
        ),
    ]
