# Generated by Django 5.2.7 on 2026-03-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_holiday_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, help_text='Student number from COR (e.g., 2022-01191). Required for students to verify COR ownership.', max_length=20, null=True, unique=True),
        ),
    ]
