# Generated by Django 5.2.7 on 2026-03-11 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_student_number_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('user_deactivated', 'User Deactivated'), ('user_reactivated', 'User Reactivated'), ('holiday_created', 'Holiday Created'), ('holiday_updated', 'Holiday Updated'), ('holiday_deleted', 'Holiday Deleted'), ('event_created', 'Calendar Event Created'), ('event_updated', 'Calendar Event Updated'), ('event_deleted', 'Calendar Event Deleted'), ('admin_login', 'Admin Login')], help_text='The type of action performed', max_length=30),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or details')),
                ('date', models.DateField(help_text='Date of the event (for recurring: only month+day matter)')),
                ('start_time', models.TimeField(blank=True, help_text='Optional start time (null = all-day event)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Optional end time', null=True)),
                ('location', models.CharField(blank=True, default='', help_text='Optional venue / location', max_length=200)),
                ('event_type', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring')], default='one_time', help_text='Whether this event repeats annually', max_length=10)),
                ('visibility', models.CharField(choices=[('all', 'All Users'), ('student', 'Students Only'), ('faculty', 'Faculty Only')], default='all', help_text='Which user roles can see this event', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='api_calenda_date_acaee6_idx'), models.Index(fields=['event_type'], name='api_calenda_event_t_f7c921_idx'), models.Index(fields=['visibility'], name='api_calenda_visibil_8aa0c8_idx')],
            },
        ),
    ]
