# Generated by Django 5.2.7 on 2026-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_calendar_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this account has been admin-verified. Faculty accounts should be verified before they can generate class codes.'),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('user_deactivated', 'User Deactivated'), ('user_reactivated', 'User Reactivated'), ('faculty_verified', 'Faculty Verified'), ('faculty_unverified', 'Faculty Unverified'), ('user_role_changed', 'User Role Changed'), ('user_profile_edited', 'User Profile Edited'), ('parent_link_created', 'Parent Link Created'), ('parent_link_revoked', 'Parent Link Revoked'), ('holiday_created', 'Holiday Created'), ('holiday_updated', 'Holiday Updated'), ('holiday_deleted', 'Holiday Deleted'), ('event_created', 'Calendar Event Created'), ('event_updated', 'Calendar Event Updated'), ('event_deleted', 'Calendar Event Deleted'), ('admin_login', 'Admin Login')], help_text='The type of action performed', max_length=30),
        ),
    ]
