# Generated by Django 5.2.7 on 2026-03-13 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_verify_existing_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original filename of the uploaded document', max_length=255)),
                ('file_type', models.CharField(help_text="File extension, e.g. 'pdf', 'jpg', 'png'", max_length=10)),
                ('upload_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], help_text='Whether this was a student or faculty COR upload', max_length=10)),
                ('extraction_method', models.CharField(choices=[('pdf_text', 'PDF Text Extraction'), ('ocr', 'OCR (Direct)'), ('ocr_fallback', 'OCR (Fallback)'), ('pdf_text_only', 'PDF Text Only (No OCR)'), ('none', 'None (Failed Before Extraction)')], default='none', help_text='Which extraction method produced the final result', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Quality score of the extraction (0.0–1.0)')),
                ('courses_extracted', models.PositiveIntegerField(default=0, help_text='Number of courses successfully extracted')),
                ('success', models.BooleanField(default=False, help_text='Whether the extraction produced usable results')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details when extraction fails')),
                ('raw_text_preview', models.TextField(blank=True, default='', help_text='First ~2000 chars of extracted text (for debugging)')),
                ('processing_time', models.FloatField(default=0.0, help_text='Total processing time in seconds')),
                ('attempts', models.JSONField(blank=True, default=list, help_text='Ordered list of extraction methods attempted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Log',
                'verbose_name_plural': 'Extraction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_extract_created_15f66d_idx'), models.Index(fields=['success'], name='api_extract_success_7f186d_idx'), models.Index(fields=['extraction_method'], name='api_extract_extract_11a87f_idx'), models.Index(fields=['upload_type'], name='api_extract_upload__85b3af_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='User-written description of the problem (max 500 chars enforced at view layer)')),
                ('upload_error', models.TextField(blank=True, default='', help_text='The system error message that was shown to the user')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved')], default='pending', help_text='Current triage status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes written by admins during investigation')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this report was marked as resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, help_text='The user who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='api_inciden_status_7b35d0_idx'), models.Index(fields=['-created_at'], name='api_inciden_created_fa6e38_idx'), models.Index(fields=['reporter', '-created_at'], name='api_inciden_reporte_ba6db0_idx')],
            },
        ),
    ]
