# Generated by Django 5.2.7 on 2026-03-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_extractionlog_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional end date for multi-day holidays (inclusive). Null means the holiday is a single day.', null=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('user_deactivated', 'User Deactivated'), ('user_reactivated', 'User Reactivated'), ('faculty_verified', 'Faculty Verified'), ('faculty_unverified', 'Faculty Unverified'), ('user_role_changed', 'User Role Changed'), ('user_profile_edited', 'User Profile Edited'), ('parent_link_created', 'Parent Link Created'), ('parent_link_revoked', 'Parent Link Revoked'), ('holiday_created', 'Holiday Created'), ('holiday_updated', 'Holiday Updated'), ('holiday_deleted', 'Holiday Deleted'), ('event_created', 'Calendar Event Created'), ('event_updated', 'Calendar Event Updated'), ('event_deleted', 'Calendar Event Deleted'), ('incident_updated', 'Incident Report Updated'), ('admin_login', 'Admin Login')], help_text='The type of action performed', max_length=30),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(help_text='Start date of the holiday (for recurring: only month+day matter)'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['end_date'], name='api_holiday_end_dat_13e40a_idx'),
        ),
    ]
