# Generated to recover a missing table on DigitalOcean
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_holiday_add_end_date'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                CREATE TABLE IF NOT EXISTS "api_passwordresetcode" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
                    "code" varchar(6) NOT NULL, 
                    "reset_token" uuid NULL UNIQUE, 
                    "is_used" boolean NOT NULL, 
                    "is_verified" boolean NOT NULL, 
                    "created_at" timestamp with time zone NOT NULL, 
                    "expires_at" timestamp with time zone NOT NULL,
                    "user_id" bigint NOT NULL CONSTRAINT "api_passwordresetcode_user_id_b4b3c06b_fk_api_user_id" REFERENCES "api_user"("id") DEFERRABLE INITIALLY DEFERRED
                );
                """,
                """
                CREATE INDEX IF NOT EXISTS "api_passwor_user_id_d63dea_idx" ON "api_passwordresetcode" ("user_id", "code");
                """,
                """
                CREATE INDEX IF NOT EXISTS "api_passwor_reset_t_38d073_idx" ON "api_passwordresetcode" ("reset_token");
                """,
                """
                CREATE INDEX IF NOT EXISTS "api_passwordresetcode_user_id_b4b3c06b" ON "api_passwordresetcode" ("user_id");
                """
            ],
            reverse_sql=migrations.RunSQL.noop
        )
    ]
