# Generated by Django 5.2.7 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_user_class_reminder_minutes_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionlog',
            name='failure_category',
            field=models.CharField(
                choices=[
                    ('none', 'None'),
                    ('no_text', 'No Text'),
                    ('parse_error', 'Parse Error'),
                    ('low_confidence', 'Low Confidence'),
                    ('metadata_mismatch', 'Metadata Mismatch'),
                    ('system_error', 'System Error'),
                ],
                default='none',
                help_text='Structured reason why extraction failed or required retry',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='llm_parse_success',
            field=models.BooleanField(
                default=False,
                help_text='Whether LLM output passed schema parsing',
            ),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='llm_used',
            field=models.BooleanField(
                default=False,
                help_text='Whether optional LLM normalization was used',
            ),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='review_required',
            field=models.BooleanField(
                default=False,
                help_text='Whether extraction output should be reviewed before trusting',
            ),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='score_breakdown',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Composite extraction score contribution per scoring component',
            ),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='template_family',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Template/profile hint for the uploaded document',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='validator_errors',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Deterministic validation errors produced by extraction validators',
            ),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['failure_category'], name='api_exlog_fail_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['template_family'], name='api_exlog_tmpl_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionlog',
            index=models.Index(fields=['review_required'], name='api_exlog_review_idx'),
        ),
    ]
