# Generated by Django 5.2.7 on 2026-03-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_extractionlog_phase1_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, default='', help_text='Stable request id supplied by client or generated server-side', max_length=64)),
                ('idempotency_key', models.CharField(help_text='Stable idempotency key to dedupe retries', max_length=128)),
                ('extraction_run_id', models.CharField(blank=True, default='', help_text='Unique extraction run id for telemetry correlation', max_length=64)),
                ('schema_version', models.CharField(default='v1', help_text='Extraction schema version used for this request', max_length=20)),
                ('upload_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10)),
                ('file_hash', models.CharField(blank=True, default='', help_text='SHA256 of uploaded file content', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_finalized', models.BooleanField(default=False, help_text='Whether the response for this key is finalized and replayable')),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User associated with this upload request', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Request',
                'verbose_name_plural': 'Extraction Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'idempotency_key'], name='api_extract_user_id_541ef2_idx'), models.Index(fields=['status'], name='api_extract_status_9d6488_idx'), models.Index(fields=['-created_at'], name='api_extract_created_76f9c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_idempotency_key')],
            },
        ),
    ]
