# Generated by Django 5.2.7 on 2026-03-25 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_extractionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public job identifier returned to the frontend on upload', primary_key=True, serialize=False)),
                ('upload_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], help_text='Whether this is a student or faculty COR upload', max_length=10)),
                ('file_name', models.CharField(blank=True, default='', help_text='Original filename of the uploaded document (for display)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', help_text='Current state of the async extraction job', max_length=20)),
                ('extraction_method', models.CharField(blank=True, choices=[('llm', 'LLM Full Parser'), ('llm_normalization', 'LLM Normalization (Stage A)'), ('regex_fallback', 'Regex Fallback'), ('none', 'None')], default='none', help_text='Which parser produced the accepted result (llm / regex_fallback)', max_length=20)),
                ('courses', models.JSONField(blank=True, help_text='Extracted courses as a JSON list. Each item mirrors the Course model fields. Null while job is pending/processing.', null=True)),
                ('student_number', models.CharField(blank=True, default='', help_text='Student number extracted from the document (student COR only)', max_length=20)),
                ('semester', models.CharField(blank=True, default='', help_text="Semester extracted from the document (e.g. '1ST', '2ND')", max_length=20)),
                ('school_year', models.CharField(blank=True, default='', help_text="School year extracted from the document (e.g. '2025-2026')", max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Composite confidence score (0.0–1.0) of the accepted extraction', null=True)),
                ('failure_category', models.CharField(blank=True, choices=[('low_confidence', 'Low Confidence'), ('parse_error', 'Parse Error'), ('no_text', 'No Text Extracted'), ('metadata_mismatch', 'Metadata Mismatch'), ('system_error', 'System Error'), ('none', 'None')], default='none', help_text="Structured reason the job failed (populated on status='failed')", max_length=30)),
                ('error_message', models.TextField(blank=True, default='', help_text='Internal error details (not shown to user, used for debugging)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who initiated this upload', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='api_extjob_user_status_idx'), models.Index(fields=['status', '-created_at'], name='api_extjob_status_created_idx'), models.Index(fields=['-created_at'], name='api_extjob_created_idx')],
            },
        ),
    ]
