# Generated by Django 5.2.7 on 2026-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_extractionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='_temp_file_path',
            field=models.TextField(blank=True, default='', help_text='Absolute path to the temp file the background thread should process. Cleared and file deleted after job reaches a terminal state.'),
        ),
    ]
