# Generated by Django 5.2.7 on 2026-04-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_extractionjob_add_temppath'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='llm_failure_reason',
            field=models.CharField(blank=True, default='', help_text='Structured LLM failure reason for this job when relevant (timeout, invalid_json, schema_reject, empty_courses)', max_length=40),
        ),
        migrations.AddField(
            model_name='extractionlog',
            name='llm_failure_reason',
            field=models.CharField(blank=True, default='', help_text='Structured LLM failure reason when parse fails (e.g. timeout, invalid_json, schema_reject, empty_courses)', max_length=40),
        ),
    ]
