# Generated by Django 5.2.7 on 2026-04-14 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_task_urgency_and_popup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUrgencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('popup_shown', 'Popup Shown'), ('snoozed', 'Snoozed'), ('acknowledged', 'Acknowledged'), ('opened', 'Opened'), ('completed_from_popup', 'Completed From Popup')], help_text='Urgency popup lifecycle event type', max_length=30)),
                ('metadata', models.JSONField(blank=True, help_text='Additional event metadata (reason, due delta, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task Urgency Event',
                'verbose_name_plural': 'Task Urgency Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='parentlinkrequest',
            new_name='api_parentl_parent__e6b7f2_idx',
            old_name='api_parentl_parent__1a4b30_idx',
        ),
        migrations.RenameIndex(
            model_name='parentlinkrequest',
            new_name='api_parentl_child_i_cfadcc_idx',
            old_name='api_parentl_child_i_a7f4be_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='api_task_user_id_92b9cb_idx',
            old_name='api_task_user_id_129589_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='api_task_user_id_3d7602_idx',
            old_name='api_task_user_id_9fa0ca_idx',
        ),
        migrations.AddField(
            model_name='facultytask',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Faculty-set urgency for this class task', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='urgent_popup_default_snooze_minutes',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '60 minutes')], default=10, help_text='Default snooze duration for urgent task popups'),
        ),
        migrations.AddField(
            model_name='user',
            name='urgent_popup_enabled',
            field=models.BooleanField(default=True, help_text='Whether invasive urgent task popups are enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='urgent_popup_quiet_hours_enabled',
            field=models.BooleanField(default=False, help_text='Whether urgent popups should be suppressed during quiet hours'),
        ),
        migrations.AddField(
            model_name='user',
            name='urgent_popup_quiet_hours_end',
            field=models.PositiveSmallIntegerField(default=7, help_text='Quiet hours end (0-23, local device hour)'),
        ),
        migrations.AddField(
            model_name='user',
            name='urgent_popup_quiet_hours_start',
            field=models.PositiveSmallIntegerField(default=22, help_text='Quiet hours start (0-23, local device hour)'),
        ),
        migrations.AddIndex(
            model_name='facultytask',
            index=models.Index(fields=['faculty', 'subject_code', 'urgency'], name='api_faculty_faculty_f6f49c_idx'),
        ),
        migrations.AddField(
            model_name='taskurgencyevent',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Related personal task (if still present)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgency_events', to='api.task'),
        ),
        migrations.AddField(
            model_name='taskurgencyevent',
            name='user',
            field=models.ForeignKey(help_text='User who triggered this urgency event', on_delete=django.db.models.deletion.CASCADE, related_name='task_urgency_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taskurgencyevent',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='api_taskurg_user_id_71b71c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskurgencyevent',
            index=models.Index(fields=['task', 'event_type'], name='api_taskurg_task_id_90f87b_idx'),
        ),
    ]
