# Generated by Django 5.2.7 on 2026-04-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_taskurgencyevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_kind', models.CharField(choices=[('personal', 'Personal Task'), ('faculty', 'Faculty Task')], help_text='Whether the reminder targets a personal or faculty task', max_length=10)),
                ('task_id', models.PositiveBigIntegerField(help_text='Primary key of the related task model')),
                ('reminder_stage', models.CharField(choices=[('due_24h', 'Due Within 24 Hours'), ('due_1h', 'Due Within 1 Hour'), ('overdue', 'Overdue')], help_text='Reminder stage window used for dedupe (24h, 1h, overdue)', max_length=10)),
                ('effective_urgency', models.CharField(default='medium', help_text='Effective urgency at dispatch time', max_length=10)),
                ('is_invasive', models.BooleanField(default=False, help_text='Whether this dispatch used invasive/urgent alert behavior')),
                ('due_date', models.DateTimeField(blank=True, help_text='Task due date at dispatch time (if available)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, help_text='Persistent Notification row associated with this dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reminder_dispatches', to='api.notification')),
                ('user', models.ForeignKey(help_text='Recipient user for this reminder dispatch', on_delete=django.db.models.deletion.CASCADE, related_name='task_reminder_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Reminder Dispatch',
                'verbose_name_plural': 'Task Reminder Dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskreminderdispatch',
            index=models.Index(fields=['user', 'task_kind', 'task_id'], name='api_taskrem_user_id_751153_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminderdispatch',
            index=models.Index(fields=['user', 'reminder_stage', '-created_at'], name='api_taskrem_user_id_2c0f49_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskreminderdispatch',
            constraint=models.UniqueConstraint(fields=('user', 'task_kind', 'task_id', 'reminder_stage'), name='unique_task_reminder_dispatch_stage'),
        ),
    ]
