# Generated by Django 5.2.7 on 2026-04-18 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_taskreminderdispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Subject code this note is associated with', max_length=50)),
                ('text', models.TextField(help_text='Quick note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'subject_code'], name='api_note_user_id_b052c0_idx'), models.Index(fields=['user', 'updated_at'], name='api_note_user_id_0791e9_idx')],
            },
        ),
    ]
