# Generated by Django 5.2.7 on 2026-04-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned', '-updated_at', '-created_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Whether this note is pinned to the top of the list'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'subject_code', 'is_pinned'], name='api_note_user_id_8c0365_idx'),
        ),
    ]
