# Generated by Django 5.2.7 on 2026-04-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_note_options_note_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('removed', 'Removed'), ('declined', 'Declined')], default='active', help_text='Status of the enrollment', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('class_reminder', 'Class Reminder'), ('faculty_task', 'Faculty Task'), ('faculty_remark', 'Faculty Remark'), ('faculty_match', 'Faculty Match'), ('general', 'General')], default='general', help_text='Type of notification', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['student', 'status'], name='api_classen_student_97ea1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'faculty', 'subject_code'), name='unique_pending_enrollment'),
        ),
    ]
