# Generated by Django 5.2.7 on 2026-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_classenrollment_pending_declined_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_verification_status',
            field=models.CharField(
                choices=[
                    ('none', 'None'),
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                ],
                default='none',
                help_text='Faculty verification workflow status: none, pending, approved, or rejected.',
                max_length=10,
            ),
        ),
    ]
