"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Define base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from the project root (SchedScan/.env)
load_dotenv(BASE_DIR.parent / ".env")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (fail-closed) — set DJANGO_DEBUG=True explicitly for local dev.
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
# In production (DEBUG=False), DJANGO_SECRET_KEY *must* be set or the app refuses to start.
# DJANGO_BUILD_PHASE is set during Docker image build to skip the check.
_secret = os.getenv("DJANGO_SECRET_KEY", "")
_build_phase = os.getenv("DJANGO_BUILD_PHASE", "") == "1"
if not _secret and not DEBUG and not _build_phase:
    raise RuntimeError(
        "DJANGO_SECRET_KEY environment variable is required in production. "
        "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )
SECRET_KEY = _secret or "dev-secret-key-NOT-FOR-PRODUCTION"

# Allow all hosts in development, use env var in production
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if os.getenv("DJANGO_ALLOWED_HOSTS") else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages',
    
    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files in production
    'corsheaders.middleware.CorsMiddleware',  # CORS - must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - supports DATABASE_URL or individual variables
import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL', '')

# Try DATABASE_URL first, fall back to individual variables
if DATABASE_URL and DATABASE_URL.startswith(('postgres://', 'postgresql://')):
    # Use DATABASE_URL if available and valid
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # Use individual environment variables
    db_port = os.getenv('DB_PORT', '5432')
    # Handle port that might come as string or with extra characters
    try:
        db_port = int(db_port) if db_port else 5432
    except (ValueError, TypeError):
        db_port = 5432
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'schedscan'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': db_port,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# DigitalOcean Spaces (S3-compatible) storage for production
# When DO_SPACES_BUCKET is set, all file uploads go to Spaces.
# Otherwise, local filesystem is used (for development).
DO_SPACES_BUCKET = os.getenv('DO_SPACES_BUCKET', '')
if DO_SPACES_BUCKET:
    AWS_ACCESS_KEY_ID = os.getenv('DO_SPACES_KEY', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('DO_SPACES_SECRET', '')
    AWS_STORAGE_BUCKET_NAME = DO_SPACES_BUCKET
    AWS_S3_REGION_NAME = os.getenv('DO_SPACES_REGION', 'sgp1')
    AWS_S3_ENDPOINT_URL = f'https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_DEFAULT_ACL = 'private'  # Files require authenticated access
    AWS_QUERYSTRING_AUTH = True  # Generate signed URLs
    AWS_QUERYSTRING_EXPIRE = 3600  # Signed URLs expire in 1 hour

    # Django 5.2 STORAGES dict (replaces deprecated DEFAULT_FILE_STORAGE
    # and STATICFILES_STORAGE settings)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Local development: use filesystem storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# File upload settings
# FILE_UPLOAD_MAX_MEMORY_SIZE: files smaller than this are held in RAM;
# larger ones stream to a temp file on disk.  Keep this low in production
# (5 files × 10 MB = 50 MB worst-case per request if held in memory).
FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440  # 2.5 MB (Django default)
# DATA_UPLOAD_MAX_MEMORY_SIZE: max size of non-file form fields only.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'admin_login': '5/min',   # brute-force protection on the admin login
    },
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://192.168.1.15:8081",
    "http://localhost:5173",       # Vite dev server (admin dashboard)
    "https://schedscan-5gfy.ondigitalocean.app",
]

# Defaults to False (fail-closed).  Set CORS_ALLOW_ALL=True for local dev only.
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'False') == 'True'

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Trusted Origins (for production API access)
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Email Configuration
# In development: emails are printed to the console (no SMTP needed)
# In production: set EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD env vars
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'SchedScan <noreply@schedscan.app>')

# Stripe Payment Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICE_AMOUNT = 8900  # ₱89.00 in centavos
STRIPE_CURRENCY = 'php'

# Notification feature flags
# Local (on-device) class reminders are the default implementation.
# Keep server-side class reminders disabled unless explicitly enabled.
ENABLE_SERVER_CLASS_REMINDERS = os.getenv('ENABLE_SERVER_CLASS_REMINDERS', 'False') == 'True'

# Extraction pipeline flags (Phase 1)
EXTRACTION_V2_ENABLED = os.getenv('EXTRACTION_V2_ENABLED', 'True') == 'True'
EXTRACTION_LLM_NORMALIZATION_ENABLED = os.getenv('EXTRACTION_LLM_NORMALIZATION_ENABLED', 'False') == 'True'
# Legacy text-LLM full-parse flag. Runtime orchestration is vision-only; this
# is retained only for backward compatibility and isolated testing.
EXTRACTION_LLM_FULL_PARSE_ENABLED = os.getenv('EXTRACTION_LLM_FULL_PARSE_ENABLED', 'False') == 'True'
EXTRACTION_ACCEPT_THRESHOLD = float(os.getenv('EXTRACTION_ACCEPT_THRESHOLD', '0.85'))
EXTRACTION_RETRY_THRESHOLD = float(os.getenv('EXTRACTION_RETRY_THRESHOLD', '0.60'))
EXTRACTION_STRICT_OWNERSHIP_MODE = os.getenv('EXTRACTION_STRICT_OWNERSHIP_MODE', 'False') == 'True'
EXTRACTION_FAST_OWNERSHIP_GATE_ENABLED = os.getenv('EXTRACTION_FAST_OWNERSHIP_GATE_ENABLED', 'True') == 'True'
EXTRACTION_FAST_OWNERSHIP_GATE_TIMEOUT_SECONDS = int(os.getenv('EXTRACTION_FAST_OWNERSHIP_GATE_TIMEOUT_SECONDS', '10'))
EXTRACTION_FAST_OWNERSHIP_GATE_MAX_PAGES = int(os.getenv('EXTRACTION_FAST_OWNERSHIP_GATE_MAX_PAGES', '1'))
EXTRACTION_FAST_OWNERSHIP_GATE_RETRY_COUNT = int(os.getenv('EXTRACTION_FAST_OWNERSHIP_GATE_RETRY_COUNT', '0'))
EXTRACTION_DEFER_STUDENT_OWNERSHIP_FOR_IMAGES = os.getenv('EXTRACTION_DEFER_STUDENT_OWNERSHIP_FOR_IMAGES', 'True') == 'True'
EXTRACTION_ASYNC_FALLBACK_ENABLED = os.getenv('EXTRACTION_ASYNC_FALLBACK_ENABLED', 'False') == 'True'
EXTRACTION_ASYNC_MAX_INFLIGHT_PER_USER = int(
    os.getenv('EXTRACTION_ASYNC_MAX_INFLIGHT_PER_USER', '1')
)
EXTRACTION_ASYNC_MAX_INFLIGHT_GLOBAL = int(
    os.getenv('EXTRACTION_ASYNC_MAX_INFLIGHT_GLOBAL', '2')
)
EXTRACTION_ASYNC_MAX_RUNNING_THREADS = int(
    os.getenv('EXTRACTION_ASYNC_MAX_RUNNING_THREADS', '1')
)
EXTRACTION_SCHEMA_VERSION = os.getenv('EXTRACTION_SCHEMA_VERSION', 'v1')
EXTRACTION_SCORE_VERSION = os.getenv('EXTRACTION_SCORE_VERSION', 'v1')
EXTRACTION_RULE_VERSION = os.getenv('EXTRACTION_RULE_VERSION', 'v1')
EXTRACTION_LLM_MODEL_NAME = os.getenv('EXTRACTION_LLM_MODEL_NAME', '')
EXTRACTION_LLM_MODEL_DIGEST = os.getenv('EXTRACTION_LLM_MODEL_DIGEST', '')
EXTRACTION_LLM_VISION_PARSE_ENABLED = os.getenv('EXTRACTION_LLM_VISION_PARSE_ENABLED', 'False') == 'True'
EXTRACTION_LLM_DIRECT_FILE_PARSE_ENABLED = os.getenv('EXTRACTION_LLM_DIRECT_FILE_PARSE_ENABLED', 'False') == 'True'
EXTRACTION_VISION_ONLY_MODE = os.getenv('EXTRACTION_VISION_ONLY_MODE', 'False') == 'True'
EXTRACTION_LLM_DIRECT_FILE_FALLBACK_ON_REJECT = (
    os.getenv(
        'EXTRACTION_LLM_DIRECT_FILE_FALLBACK_ON_REJECT',
        'False' if EXTRACTION_VISION_ONLY_MODE else 'True',
    )
    == 'True'
)
EXTRACTION_LLM_VISION_MODEL_NAME = os.getenv('EXTRACTION_LLM_VISION_MODEL_NAME', '')
EXTRACTION_LLM_VISION_MODEL_DIGEST = os.getenv('EXTRACTION_LLM_VISION_MODEL_DIGEST', '')
EXTRACTION_LLM_VISION_REQUIRE_PINNED_MODEL = os.getenv('EXTRACTION_LLM_VISION_REQUIRE_PINNED_MODEL', 'True') == 'True'
EXTRACTION_LLM_VISION_REQUIRE_MODEL_DIGEST = os.getenv('EXTRACTION_LLM_VISION_REQUIRE_MODEL_DIGEST', 'False') == 'True'
EXTRACTION_LLM_VISION_MAX_PAGES = int(os.getenv('EXTRACTION_LLM_VISION_MAX_PAGES', '3'))
EXTRACTION_LLM_VISION_RETRY_COUNT = int(os.getenv('EXTRACTION_LLM_VISION_RETRY_COUNT', '1'))
EXTRACTION_LLM_BASE_URL = os.getenv('EXTRACTION_LLM_BASE_URL', 'http://127.0.0.1:11434')
EXTRACTION_LLM_TIMEOUT_SECONDS = int(os.getenv('EXTRACTION_LLM_TIMEOUT_SECONDS', '12'))
EXTRACTION_LLM_VISION_CONNECT_TIMEOUT_SECONDS = int(
    os.getenv('EXTRACTION_LLM_VISION_CONNECT_TIMEOUT_SECONDS', '8')
)
EXTRACTION_LLM_VISION_MAX_TOKENS = int(os.getenv('EXTRACTION_LLM_VISION_MAX_TOKENS', '768'))
EXTRACTION_LLM_VISION_RETRY_MAX_TOKENS = int(
    os.getenv('EXTRACTION_LLM_VISION_RETRY_MAX_TOKENS', '576')
)
EXTRACTION_LLM_VISION_IMAGE_MAX_EDGE = int(os.getenv('EXTRACTION_LLM_VISION_IMAGE_MAX_EDGE', '1600'))
EXTRACTION_LLM_VISION_IMAGE_QUALITY = int(os.getenv('EXTRACTION_LLM_VISION_IMAGE_QUALITY', '72'))
EXTRACTION_LLM_VISION_RETRY_IMAGE_MAX_EDGE = int(
    os.getenv('EXTRACTION_LLM_VISION_RETRY_IMAGE_MAX_EDGE', '1280')
)
EXTRACTION_LLM_VISION_RETRY_IMAGE_QUALITY = int(
    os.getenv('EXTRACTION_LLM_VISION_RETRY_IMAGE_QUALITY', '68')
)
EXTRACTION_LLM_VISION_PDF_DPI = int(os.getenv('EXTRACTION_LLM_VISION_PDF_DPI', '220'))
EXTRACTION_LLM_VISION_RETRY_PDF_DPI = int(os.getenv('EXTRACTION_LLM_VISION_RETRY_PDF_DPI', '180'))
EXTRACTION_LLM_VISION_ADAPTIVE_BUDGET_ENABLED = (
    os.getenv('EXTRACTION_LLM_VISION_ADAPTIVE_BUDGET_ENABLED', 'True') == 'True'
)
EXTRACTION_LLM_VISION_ADAPTIVE_GRAYSCALE_ENABLED = (
    os.getenv('EXTRACTION_LLM_VISION_ADAPTIVE_GRAYSCALE_ENABLED', 'True') == 'True'
)
EXTRACTION_LLM_VISION_ADAPTIVE_FIRST_PASS_TIMEOUT_SECONDS = int(
    os.getenv('EXTRACTION_LLM_VISION_ADAPTIVE_FIRST_PASS_TIMEOUT_SECONDS', '90')
)
EXTRACTION_LLM_VISION_ADAPTIVE_FILE_SIZE_MB_LARGE = float(
    os.getenv('EXTRACTION_LLM_VISION_ADAPTIVE_FILE_SIZE_MB_LARGE', '3.0')
)
EXTRACTION_LLM_VISION_ADAPTIVE_FILE_SIZE_MB_HUGE = float(
    os.getenv('EXTRACTION_LLM_VISION_ADAPTIVE_FILE_SIZE_MB_HUGE', '7.0')
)
EXTRACTION_LLM_VISION_ADAPTIVE_IMAGE_MP_LARGE = float(
    os.getenv('EXTRACTION_LLM_VISION_ADAPTIVE_IMAGE_MP_LARGE', '4.0')
)
EXTRACTION_LLM_VISION_ADAPTIVE_IMAGE_MP_HUGE = float(
    os.getenv('EXTRACTION_LLM_VISION_ADAPTIVE_IMAGE_MP_HUGE', '10.0')
)
EXTRACTION_LLM_VISION_CHUNKING_ENABLED = (
    os.getenv('EXTRACTION_LLM_VISION_CHUNKING_ENABLED', 'True') == 'True'
)
EXTRACTION_LLM_VISION_CHUNKING_FORCE_ENABLED = (
    os.getenv('EXTRACTION_LLM_VISION_CHUNKING_FORCE_ENABLED', 'False') == 'True'
)
EXTRACTION_LLM_VISION_CHUNK_COUNT = int(
    os.getenv('EXTRACTION_LLM_VISION_CHUNK_COUNT', '3')
)
EXTRACTION_LLM_VISION_CHUNK_OVERLAP_RATIO = float(
    os.getenv('EXTRACTION_LLM_VISION_CHUNK_OVERLAP_RATIO', '0.12')
)
EXTRACTION_LLM_VISION_CHUNKING_MIN_HEIGHT_PX = int(
    os.getenv('EXTRACTION_LLM_VISION_CHUNKING_MIN_HEIGHT_PX', '900')
)
EXTRACTION_LLM_VISION_CHUNKING_MAX_CHUNKS = int(
    os.getenv('EXTRACTION_LLM_VISION_CHUNKING_MAX_CHUNKS', '4')
)
EXTRACTION_LLM_VISION_METADATA_IMAGE_MAX_EDGE = int(
    os.getenv('EXTRACTION_LLM_VISION_METADATA_IMAGE_MAX_EDGE', '960')
)
EXTRACTION_LLM_VISION_METADATA_IMAGE_QUALITY = int(
    os.getenv('EXTRACTION_LLM_VISION_METADATA_IMAGE_QUALITY', '52')
)
EXTRACTION_LLM_VISION_METADATA_PDF_DPI = int(
    os.getenv('EXTRACTION_LLM_VISION_METADATA_PDF_DPI', '150')
)
EXTRACTION_LLM_VISION_METADATA_GRAYSCALE_ENABLED = (
    os.getenv('EXTRACTION_LLM_VISION_METADATA_GRAYSCALE_ENABLED', 'True') == 'True'
)
EXTRACTION_LLM_MAX_INPUT_CHARS = int(os.getenv('EXTRACTION_LLM_MAX_INPUT_CHARS', '6000'))
EXTRACTION_LLM_VISION_RETRY_TIMEOUT_SECONDS = int(
    os.getenv('EXTRACTION_LLM_VISION_RETRY_TIMEOUT_SECONDS', str(EXTRACTION_LLM_TIMEOUT_SECONDS))
)
EXTRACTION_LLM_VISION_RETRY_MAX_PAGES = int(
    os.getenv('EXTRACTION_LLM_VISION_RETRY_MAX_PAGES', str(max(EXTRACTION_LLM_VISION_MAX_PAGES, 2)))
)
# Legacy text-model settings kept for backward compatibility.
EXTRACTION_LLM_REQUIRE_PINNED_MODEL = os.getenv('EXTRACTION_LLM_REQUIRE_PINNED_MODEL', 'True') == 'True'
EXTRACTION_LLM_REQUIRE_MODEL_DIGEST = os.getenv('EXTRACTION_LLM_REQUIRE_MODEL_DIGEST', 'False') == 'True'
EXTRACTION_LLM_STARTUP_CHECK_ENABLED = os.getenv('EXTRACTION_LLM_STARTUP_CHECK_ENABLED', 'False') == 'True'
EXTRACTION_LLM_STARTUP_CHECK_STRICT = os.getenv('EXTRACTION_LLM_STARTUP_CHECK_STRICT', 'False') == 'True'
EXTRACTION_LLM_STARTUP_CHECK_TIMEOUT_SECONDS = int(os.getenv('EXTRACTION_LLM_STARTUP_CHECK_TIMEOUT_SECONDS', '2'))
EXTRACTION_RECOVER_STALE_JOBS_ON_STARTUP = os.getenv('EXTRACTION_RECOVER_STALE_JOBS_ON_STARTUP', 'False') == 'True'
EXTRACTION_STALE_JOB_MAX_AGE_MINUTES = int(os.getenv('EXTRACTION_STALE_JOB_MAX_AGE_MINUTES', '5'))
# API key sent in the X-Api-Key header to the nginx reverse proxy in front of Ollama.
# Empty string (default) = no header sent — backward-compatible for local dev where Ollama
# is accessed directly on 127.0.0.1:11434 without a proxy.
# In production: set this to the value generated by `openssl rand -hex 32` on the Droplet.
EXTRACTION_LLM_API_KEY = os.getenv('EXTRACTION_LLM_API_KEY', '')

# Cloud LLM provider routing.
# 'ollama' = existing self-hosted Ollama (default, backward-compatible).
# 'gemini' = Google Gemini API (free tier via AI Studio).
# 'groq'   = Groq API (free tier).
# 'cloud'  = try gemini then groq.
# 'auto'   = try gemini → groq → Ollama fallback.
EXTRACTION_LLM_PROVIDER = os.getenv('EXTRACTION_LLM_PROVIDER', 'ollama')
EXTRACTION_GEMINI_API_KEY = os.getenv('EXTRACTION_GEMINI_API_KEY', '')
EXTRACTION_GEMINI_MODEL = os.getenv('EXTRACTION_GEMINI_MODEL', 'gemini-2.5-flash-lite')
EXTRACTION_GROQ_API_KEY = os.getenv('EXTRACTION_GROQ_API_KEY', '')
EXTRACTION_GROQ_MODEL = os.getenv('EXTRACTION_GROQ_MODEL', 'meta-llama/llama-4-scout-17b-16e-instruct')
EXTRACTION_CLOUD_TIMEOUT_SECONDS = int(os.getenv('EXTRACTION_CLOUD_TIMEOUT_SECONDS', '30'))

# Optional override for parser priors used by composite confidence scoring.
EXTRACTION_PARSER_RELIABILITY_PRIOR = {
    'pdf_text': float(os.getenv('EXTRACTION_PRIOR_PDF_TEXT', '0.92')),
    'llm_vision_parse': float(os.getenv('EXTRACTION_PRIOR_LLM_VISION_PARSE', '0.93')),
    'llm_full_parse': float(os.getenv('EXTRACTION_PRIOR_LLM_FULL_PARSE', '0.90')),
    'llm_normalize': float(os.getenv('EXTRACTION_PRIOR_LLM_NORMALIZE', '0.85')),
    'ocr': float(os.getenv('EXTRACTION_PRIOR_OCR', '0.74')),
    'ocr_fallback': float(os.getenv('EXTRACTION_PRIOR_OCR_FALLBACK', '0.68')),
    'pdf_text_only': float(os.getenv('EXTRACTION_PRIOR_PDF_TEXT_ONLY', '0.60')),
    'none': 0.0,
}

# Optional score-weight policy by upload type.
# Student defaults mirror existing global weights.
# Faculty gets slightly higher completeness/consistency weight to better account
# OCR-corrected rows where deterministic validity has already passed.
EXTRACTION_SCORE_WEIGHTS_BY_UPLOAD_TYPE = {
    'student': {
        'completeness': float(os.getenv('EXTRACTION_STUDENT_WEIGHT_COMPLETENESS', '0.25')),
        'validity': float(os.getenv('EXTRACTION_STUDENT_WEIGHT_VALIDITY', '0.25')),
        'consistency': float(os.getenv('EXTRACTION_STUDENT_WEIGHT_CONSISTENCY', '0.20')),
        'parser_reliability': float(os.getenv('EXTRACTION_STUDENT_WEIGHT_PARSER_RELIABILITY', '0.15')),
        'agreement': float(os.getenv('EXTRACTION_STUDENT_WEIGHT_AGREEMENT', '0.15')),
    },
    'faculty': {
        'completeness': float(os.getenv('EXTRACTION_FACULTY_WEIGHT_COMPLETENESS', '0.30')),
        'validity': float(os.getenv('EXTRACTION_FACULTY_WEIGHT_VALIDITY', '0.25')),
        'consistency': float(os.getenv('EXTRACTION_FACULTY_WEIGHT_CONSISTENCY', '0.25')),
        'parser_reliability': float(os.getenv('EXTRACTION_FACULTY_WEIGHT_PARSER_RELIABILITY', '0.10')),
        'agreement': float(os.getenv('EXTRACTION_FACULTY_WEIGHT_AGREEMENT', '0.10')),
    },
}

# Optional threshold policy by upload type.
EXTRACTION_ACCEPT_THRESHOLD_BY_UPLOAD_TYPE = {
    'student': float(os.getenv('EXTRACTION_ACCEPT_THRESHOLD_STUDENT', str(EXTRACTION_ACCEPT_THRESHOLD))),
    'faculty': float(os.getenv('EXTRACTION_ACCEPT_THRESHOLD_FACULTY', str(EXTRACTION_ACCEPT_THRESHOLD))),
}

EXTRACTION_RETRY_THRESHOLD_BY_UPLOAD_TYPE = {
    'student': float(os.getenv('EXTRACTION_RETRY_THRESHOLD_STUDENT', str(EXTRACTION_RETRY_THRESHOLD))),
    'faculty': float(os.getenv('EXTRACTION_RETRY_THRESHOLD_FACULTY', str(EXTRACTION_RETRY_THRESHOLD))),
}

# ---------------------------------------------------------------------------
# Production security hardening
# DigitalOcean App Platform terminates TLS at the load-balancer and forwards
# X-Forwarded-Proto. These settings ensure Django knows the request was HTTPS.
# ---------------------------------------------------------------------------
if not DEBUG:
    # Tell Django to trust the X-Forwarded-Proto header from DO's load balancer
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Redirect all HTTP → HTTPS
    SECURE_SSL_REDIRECT = True

    # HSTS: tell browsers to only use HTTPS for 1 year (include subdomains)
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies: only send over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Prevent the browser from MIME-sniffing the content type
    SECURE_CONTENT_TYPE_NOSNIFF = True

