name: schedscan
region: sgp

services:
  - name: schedscan-api
    source_dir: /backend
    dockerfile_path: Dockerfile
    github:
      repo: SheerMichael/SchedScan
      branch: main
      deploy_on_push: true
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    http_port: 8080
    envs:
      - key: DJANGO_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_TIME
        value: ${APP_DOMAIN}
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: CORS_ALLOW_ALL
        value: "False"
    routes:
      - path: /

databases:
  - name: db
    engine: PG
    production: false
    cluster_name: schedscan-db
